### ISSUE TITLE
bottomSheet is always rebuild

### ISSUE THREAD

**Issue by klaszlo8207** [jonataslaw/get#21] opened 2020-03-11 09:26 UTC
I have a 

  Get.bottomSheet(
      isScrollControlled: true,
      builder: (_) => MySheetWidget(title));

MySheetWidget is a statefulwidget

When i move the sheet top/bottom the build method always triggering

**Comment by klaszlo8207** [comment] 2020-03-11 10:46
Sorry I did it:

builder: (_) => MySheetWidget(title));

instead of, better:

final page = MySheetWidget(title));

builder: (_) => page;

**Comment by klaszlo8207** [comment] 2020-04-17 18:34
Sorry I reopen it.

I need that the bottomSheet no rebuild when I resize it. (builder is always build when scrolling) 

Any way to do that?

**Comment by jonataslaw** [comment] 2020-04-18 02:55
Please ask support questions on appropriate channels like stackoverflow.
Get just opens the BottomSheet with the overlayContext.
You can even use default Flutter's bottomsheet with Get.overlayContext

```dart
 showModalBottomSheet(
      context: Get.overlayContext, // rather context
      builder: (BuildContext bc){
          return Container(
            child: new Wrap(
            children: <Widget>[
        ListTile(
            leading:  Icon(Icons.music_note),
            title:  Text('Music'),
            onTap: () => {}          
          ),
           ListTile(
            leading:  Icon(Icons.videocam),
            title:  Text('Video'),
            onTap: () => {},          
          ),
          ],
          ),
        );
      }
    );
```
So, your issue is not a bug description or a resource request, and I can't help you here.

Put your question on the stackoverflow and I can answer you there.

I just make it clear here, that the bottomsheet is rebuilt with each dragged pixel. You cannot change this behavior, because without the reconstruction, it would not change in size (it is the size change that causes the reconstruction), so if there is any side effect to this, the problem is in the logic of your code.

Advices:

1- Always create a Stateful widget, and call the bottomsheet with it inside:
Get.bottomsheet (builder: (_) => const YourStatefulClass ());
2- Use Stateful, never Stateless if you want something to remain in a state. Never place controllers inside the build method, but at the beginning of the class.
3- Use const in the class builder, and call your class const, this will totally prevent your child widget from being rebuilt when the parent (bottomsheet) is rebuilt.

If you have questions related to the library, (and not when Flutter widgets work), do not hesitate to open another issue.
Closing by offtopic.

**Closed by jonataslaw** 2020-04-18 02:55 UTC
