### ISSUE TITLE
[Proposal] Way to change transition for ALL pages at once

### ISSUE THREAD

**Issue by jlubeck** [jonataslaw/get#39] opened 2020-04-15 20:14 UTC
From what I'm understanding, you need to change each route to change its transition. 
Would be nice to just set it globally once for all of them. 

Use case, I want to have everything fade instead of default

**Comment by jonataslaw** [comment] 2020-04-15 21:39
> From what I'm understanding, you need to change each route to change its transition.
> Would be nice to just set it globally once for all of them.
> 
> Use case, I want to have everything fade instead of default

Hi, this is very anti-pattern.
I understand that you want this feature to make your job easier, but you cannot change all routes transitions in your app, it will not be accepted by the AppStore.
I created GetPlatform in the last update to identify the platform being used and use the native one by default because I had an application declined in the AppleStore for using transitions not compatible with Human Guidelines.
So even if you forget to define a transition, the default will still be the native one.
Transitions are created to be used casually, on android you can change as you like, but on iOS you will need the native transition, or your app will be declined.
Obviously using some transitions in your app in fade will not make it be rejected, but the transitions of the main screen, if they have a very different transition, manual analysis will decline your app.
And this is not just me, I have devs friends who work in companies like Facebook, and in a conversation they told me that they, which are giants, have already had updates refused, imagine smaller companies. Facebook has even adopted the cupertino transition by default for Facebook (if you open your Facebook application on an android now, you will see that the transition is all cupertino) because android approves anything, but iOS does not, at least for now. Google has also changed the policy of accepting apps a lot, icons that could be literally anything, now only material icons are accepted, and I believe that in the future they can also become strict, and at that point, it is better to follow the rules of the material, which makes it clear that Android transitions must have a "material fade" effect.
That said, I have no intention of defining this feature, as I find it harmful for less experienced people, who may for lack of information have their application rejected, at least for now, in the AppleStore.
And I advise you that unless you intend to launch an Android-only app, don't abuse Transitions.fade. It moves to Mac programs (I have one in the store with Flutter), but not iOS.

**Comment by jlubeck** [comment] 2020-04-15 21:42
I'm building a web app, not an iOS app

**Comment by jonataslaw** [comment] 2020-04-15 22:12
In the next update I will improve Get.config on the stable branch (currently this feature is only available on stable, because a lot has changed in the Framework on the dev that made it difficult to launch this feature) and I will launch it on the dev branch, and maybe I add the option to have a standard transition.
I will also decide whether or not to launch the "defaultTransition", and if I do, I will make it explicit in the documentation that for multiplatform applications this would be a bad practice, but that for uniplataforms applications it can be useful.
If I include this in Get.config, I will mark this issue to let you know, but I will close it for now.

**Comment by jonataslaw** [comment] 2020-04-16 01:53
Added on lastest update

use:
Get.config(defaultTransition: Transitions.fade);

**Closed by jonataslaw** 2020-04-16 01:53 UTC

**Comment by jlubeck** [comment] 2020-04-16 16:28
so great to hear that you implemented this!
Unfortunately it is not working for me. 
I went quickly through the source code, and although I see it implemented on get_main.dart I don't see it being used on GetRoute anywhere... I might have overlooked something, but since it is not working, there might be something missing?

At the same time, if this needs fixing, it would be nice to also have a defaultTransitionDuration

**Comment by jonataslaw** [comment] 2020-04-16 17:07
I just tested this on android, iOS, web and desktop, and they both work properly.

See the following reproduction code:

```dart
import 'package:flutter/material.dart';
import 'package:get/get.dart';

void main() {
  Get.config(defaultTransition: Transition.downToUp);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(),
      navigatorKey: Get.key,
      home: First(),
    );
  }
}

class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.add),
          onPressed: () {
            Get.snackbar("hi", "i am a modern snackbar");
          },
        ),
        title: Text('First Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            Get.to(Second());
          },
        ),
      ),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.add),
          onPressed: () {
            Get.snackbar("hi", "i am a modern snackbar");
          },
        ),
        title: Text('second Route'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Open route'),
          onPressed: () {
            Get.to(Third());
          },
        ),
      ),
    );
  }
}

class Third extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Third Route"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Get.back();
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

**Comment by jonataslaw** [comment] 2020-04-21 21:31
My test was using common routes, and it was passing everything. I included a test with named routes and it failed at some points in Get.config in previous versions. I think the named routes were ignoring the feature somewhere in GetRoute, so I decided to centralize everything in the same resource and access it through a get to avoid any problem or human error. If there was still an error with Get.config it was fixed in the latest version, where all features were extensively tested to backport to the stable branch. This should definitely be working now.

**Comment by jlubeck** [comment] 2020-04-22 18:20
Yup! This is working great now! You are great

How do you feel about adding a defaultTransitionDuration as well??

**Comment by jonataslaw** [comment] 2020-04-22 19:12
> Yup! This is working great now! You are great
> 
> How do you feel about adding a defaultTransitionDuration as well??

I will probably add it in the next update, the last issue made me wonder if I should create a parameter in Get.back () to make it optional to close snackbars/modals together with Get.back() and make this also a global configuration parameter, but that would force people to add GetObserver in addition to Get.key. I don't know if people prefer this, or a Widget inherited from MaterialApp as a GetMaterialApp that already has all the necessary settings, and it was possible to make the Global settings directly on it.
The second option seems to be easier, however it can seem aggressive to Dev to change a widget that level.
I am safe to do so because I have been using the Library in more than 30 apps for almost a year (this was my internal Library before opening opensource), and 2 of them have more than 2 million active users per day. I know that Get is more stable than even the standard Navigator, there are many hotfixes that have dozens of issues open on Flutter (like SafeArea on BottomSheet), but users who find the library may not know it.

**Comment by ruziyi** [comment] 2020-06-18 08:41
This doesn't work on 1.17.1
