### ISSUE TITLE
How to set showModalBottomSheet to full height but below status bar?

### ISSUE THREAD

**Issue by klaszlo8207** [jonataslaw/get#44] opened 2020-04-17 17:22 UTC
How can I do this?

**Comment by jonataslaw** [comment] 2020-04-18 02:46
Please ask support questions on appropriate channels like stackoverflow.
Get just opens the BottomSheet with the overlayContext.
You can even use default Flutter's bottomsheet with Get.overlayContext

```dart
 showModalBottomSheet(
      context: Get.overlayContext, // rather context
      builder: (BuildContext bc){
          return Container(
            child: new Wrap(
            children: <Widget>[
        ListTile(
            leading:  Icon(Icons.music_note),
            title:  Text('Music'),
            onTap: () => {}          
          ),
           ListTile(
            leading:  Icon(Icons.videocam),
            title:  Text('Video'),
            onTap: () => {},          
          ),
          ],
          ),
        );
      }
    );
```
So, your issue is not a bug description or a resource request, and I can't help you here.

Put your question on the stackoverflow and I can answer you there.
If you have questions related to the library, (and not when Flutter widgets work), do not hesitate to open another issue.
Closing by offtopic.

**Comment by klaszlo8207** [comment] 2020-04-18 04:35
I want with Get.bottomSheet, I tried to wrap in SafeArea but not worked. In your library how can I do that?

**Comment by jonataslaw** [comment] 2020-04-18 06:55
I understand, this is a problem with Flutter's PopupRoute.
No one widget that uses PopupRoute respect to the SafeArea (BottomSheets, PopupMenu, etc.).

You can see more examples in these open issues in Flutter:

https://github.com/flutter/flutter/issues/48677
https://github.com/flutter/flutter/issues/39205

The error is very easy to solve, the problem is in this line 469:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/bottom_sheet.dart


```dart
 Widget bottomSheet = MediaQuery.removePadding(
      context: context,
      removeTop: true, // HERE
```

In my opinion, removePadding should only be activated if it receives a bool per parameter to be able to disable this behavior.

```dart
 _ModalBottomSheetRoute({
    this.builder,
    this.theme,
    this.barrierLabel,
    this.backgroundColor,
    this.removeTop = true, // add this
    this.elevation,
    this.shape,
    this.clipBehavior,
    this.modalBarrierColor,
    this.isDismissible = true,
    this.enableDrag = true,
    @required this.isScrollControlled,
    RouteSettings settings,
  }) : assert(isScrollControlled != null),
       assert(isDismissible != null),
       assert(enableDrag != null),
       super(settings: settings);

  final WidgetBuilder builder;
  final ThemeData theme;
  final bool isScrollControlled;
  final bool removeTop; // add this
[...]

 Widget bottomSheet = MediaQuery.removePadding(
      context: context,
      removeTop: removeTop, // CHANGE FOR IT

```
In 3 lines, the problem in the Framework has been solved. You can rely on that to offer a PR on Git do Flutter, or even here on Get.

However, they will demand tests, and tests, and more tests to pass the PR, and I don't know if I have time for that.

I may include this in my lib in the future, but it is not a priority now.
If you want you can work on a PR on the lib, which I will gladly accept.

**Comment by jonataslaw** [comment] 2020-04-19 06:55
Added on 1.18.0-dev

```dart
 Get.bottomSheet(
            isScrollControlled: true,
            ignoreSafeArea: false, // add this
            builder: (_) {
              return SafeArea( // and this
                child: Container(
                  child: new Column(
                    children: <Widget>[
                      Expanded(
                          child: Container(
                              color: Colors.red,
                              child: Center(
                                child: Text("text"),
                              )))
                    ],
                  ),
                ),
              );
            });
```

As it is about adding a feature and not fixing a bug, there will be no backport to the stable version of Get, you need to be in the beta/dev/master branch of Flutter to be able to test this.

**Closed by jonataslaw** 2020-04-19 06:55 UTC

**Comment by juliavi** [comment] 2020-08-11 14:13
Give the chid container a height - based X% from the context's height, based on a MediaQuery

**Comment by Zeehshan** [comment] 2021-08-22 17:29
User IntrinsicHeight

**Comment by MrCsabaToth** [comment] 2022-08-22 07:27
This issue becomes very important for every mobile app which allows device rotation: as soos as the device is rotated into landscape mode the sheet only occupies just a little more than a half of the screen and the content gets squashed and distorted easily.

**Comment by MrCsabaToth** [comment] 2022-08-26 21:40
The linter complains about unnecessary `Container` in Jonathan's code so I brought it up to date (+ removal of `new`, `<Widget>`):

```
          Get.bottomSheet(
            SafeArea(
              child: Column(
                children: [
                  Expanded(
                    child: Container(
                      color: Colors.red,
                      child: Center(
                        child: Text("text"),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            isScrollControlled: true,
            ignoreSafeArea: false,
          );
```

**Comment by pzehle** [comment] 2023-03-02 20:34
@MrCsabaToth your code will still leave a weird area in the bottom:

![Screenshot 2023-03-02 at 21 33 40](https://user-images.githubusercontent.com/27866874/222545605-37a2cd53-49be-4cfd-b933-2826a9f974df.png)

Any idea on how to actually make it fullscreen?

**Comment by MrCsabaToth** [comment] 2023-03-02 21:12
> @pzehle: Any idea on how to actually make it fullscreen?

That's interesting! I have a feeling this might be affected by screen settings. On Android there are ways to configure how the notch area is handled. On Android it's version dependent and I cannot find a good article, but there's a way to configure if the status bar area should be excluded from the app's estate, or the app's screen flow into it and the status bar icons overlay over it. https://thenextweb.com/news/how-to-change-your-android-status-bar

I see you are on iPhone, I wonder if there's settings for that as well. I'm bringing this up because that ugly see through space on the bottom happens to have kinda similar height as the status bar area with the notch, and I wonder if this is some effect that because the phone is configured to offer the whole status bar area for the app and now the parameters we use end up "shifting" the red area all the way up to the top, rather than leaving the status bar alone. Obviously it should work with this configuration as well, this looks like a UX bug, not sure if it's in GetX, or some core Flutter one. The best case scenario is if we can figure out how to work this around with some more parametrization of the SafeArea or related widgets.

Here is a screenshot of my OnePlus Nord, Android 12 (these settings evolved over versions), and here is a related setting:
![Screenshot_2023-03-02-12-39-59-90_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/744949/222554561-3bcfffe1-83fd-4629-8e79-d5d628228c3a.jpg)

I cannot remember where I configured it, or if I configured the notch behavior at all. Right now if I try some of my native Android augmented reality apps which supposed to be full screen also exclude the status bar area. I won't have time to play with this because I'm tied down, but I'm very interested in it, because if it happens with you it can happen with my users as well.

**Comment by MrCsabaToth** [comment] 2023-03-02 21:13
Maybe a follow-up issue if needed because this is closed, or reopen this. Maybe we'll find a workaround.

**Comment by pzehle** [comment] 2023-03-02 21:17
Thank you for a very detailed answer and explanation. Yeah, it seems weird to me as well, and I have no clue what might be triggering this. I need to deliver this soon, so I will keep you posted if I find the solution or anything at all.

Thanks!
