### ISSUE TITLE
Still experiencing issues with streams not being closed

### ISSUE THREAD

**Issue by MichaelOttink** [jonataslaw/get#102] opened 2020-05-14 12:48 UTC
**Describe the bug**
I pulled the last version but I still experience memory problem because streams don't get closed.

I have 2 widgets, the first widget navigates to the second widget. In my second widget It have a GetBuilder which builds a controller and that controller adds a stream to a stream controller upon the state initialization.

I ran some memory tests and noticed that stream never closes but I does print to the console that the functions get invoked. I made a example which demonstrates this very clearly.

**To Reproduce**

Just run this code and click the button a few times to switch pages and you'll start to see the prints pile up.

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:rxdart/rxdart.dart';

class TestWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      child: Text('go to widget 2'),
      onPressed: () => Get.to(TestWidget2()),
    );
  }
}

class TestWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<GetStreamController<void>>(
      init: GetStreamController(_periodicStream()),
      builder: (GetStreamController controller) => RaisedButton(
        child: Text('go to back'),
        onPressed: () => Get.back(),
      ),
    );
  }

  Stream<void> _periodicStream() {
    return Stream.periodic(Duration(seconds: 1), (int tick) => print('seconds : $tick'));
  }
}

class GetStreamController<T> extends GetController {
  final Stream<T> value;
  StreamController<T> _streamController = BehaviorSubject();
  Stream<T> get stream => _streamController.stream;

  GetStreamController(this.value);

  @override
  void initState() {
    _streamController.addStream(value);
    super.initState();
    print('${T.toString()} stream init');
  }

  @override
  void dispose() {
    _streamController.close();
    super.dispose();
    print('${T.toString()} stream dispose');
  }

  @override
  void close() {
    print('close');
    closeStream();
    super.close();
  }

  Future<void> closeStream() async {
    print('start close');
    try {
      await stream.drain();
      _streamController.close();
    } catch (error) {
      print(error);
    }
    print('${T.toString()} stream closed');
  }
}


```

O btw I have these running in a GetMaterialApp ofc. But I have some sensetive info in there so I did not copy that file.

**Expected behavior**
I expect the streams to close when the Controller get's either closed of disposed

**Screenshots**
This is what I see when I analyze my memory, it keeps piling up everytime I switch page

![image](https://user-images.githubusercontent.com/15832303/81935911-a53b3800-95f1-11ea-83ef-a422984df587.png)

**Flutter Version:**
1.17.1

**Get Version:**
get: ^2.4.0

**Describe on which device you found the bug:**
Android Emultator

**Edit**
I just noticed that it never reaches `print('${T.toString()} stream closed');`  But it does get to `print('start close');` I put a try catch around the code that closes the stream but no error is being thrown?

**Comment by jonataslaw** [comment] 2020-05-14 13:35
I think that maybe you are creating a memory leak by adding a stream to a controller that has already been instantiated, the first instance of that controller goes to Narnia and is not removed by the garbage collector. Why don't you use a StreamSubscription instead? the addStream method is generally a memoryLeak factory in the dart that should not be used.

How controllers work:

String name = "camila";
name = "fernanda";
// Object was exchanged, without memory Leak

StreamController is just an interface that creates a sink.
StreamController controller = StreamController ();
// sink created and attached to this controller, Behavior Subject is a StreamController;
// stream is created and signed as output from that controller.

controller.addStream(newStream);

// StreamController references the new stream, and the old one went to Narnia.

Note: It went to Narnia = lost the reference and cannot be cleaned by the GC, it literally went into limbo.

I will check if there is any try/catch in the close method preventing debugging, but probably the problem is adding this stream.

**Comment by MichaelOttink** [comment] 2020-05-14 14:18
Hey thanks for the quick response! I am using a stream controller because I am using the StreamBuilder Widget. I want the stream to be used by multiple StreamBuilders so I used the BehaviourSubject. Is there any other way to do this with a GetController?

**Comment by jonataslaw** [comment] 2020-05-14 14:18
Try:

class TestWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      child: Text('go to widget 2'),
      onPressed: () => Get.to(TestWidget2()),
    );
  }
}

class TestWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetBuilder<GetStreamController<void>>(
      init: GetStreamController(_periodicStream()),
      dispose: (_) => stream,
      builder: (GetStreamController controller) => RaisedButton(
        child: Text('go to back'),
        onPressed: () => Get.back(),
      ),
    );
  }

  final stream = Stream.periodic(
      Duration(seconds: 1), (int tick) => print('seconds : $tick'));
  Stream<void> _periodicStream() {
    return stream;
  }
}

class GetStreamController<T> extends GetController {
  final Stream<T> value;
  StreamController<T> _streamController = StreamController();
  StreamSubscription _subscription;
  Stream<T> get stream => _streamController.stream;

  GetStreamController(this.value);

  @override
  void initState() {
    _subscription = value.listen((event) {
      _streamController.add(event);
    });
    super.initState();
    print('${T.toString()} stream init');
  }

  @override
  void dispose() {
    _streamController.close();
    super.dispose();
    print('${T.toString()} stream dispose');
  }

  @override
  void close() {
    print('close');
    _subscription.cancel();
    closeStream();
    super.close();
  }

  Future<void> closeStream() async {
    print('start close');
    try {
      await stream?.drain();
      _streamController.close();
    } catch (error) {
      print(error);
    }
    print('${T.toString()} stream closed');
  }
}

Well, here is an example of StreamSubscription that solves your problem.

For the sake of your code NEVER use the addStream method again, this API should definitely be removed from Dart and I don't know how on such a large team they missed it.

**Comment by jonataslaw** [comment] 2020-05-14 14:26
Just to make it clear:
- The AddStream method is a memoryLeak factory and cannot be used safely.
- The only safe way to pass the content of a stream to a streamController is using the StreamSubscription, it is one more step of code, but unfortunately there is nothing to do, with GetX maybe I can make the wrapper safe with this, since I'm getting my hands dirty to build efficient reactive APIs (rx has memory leak everywhere).

Lastly, you don't need an RX BehaviorSubject for this, you can use it too, but a

StreamController <T> _streamController = StreamController.broadcast(); // broadcast allow multiple listeners

would solve your problem.

**Comment by jonataslaw** [comment] 2020-05-14 14:46
Based on the reproduction code, and since close is called properly and the memory leak is from addStream, I'm closing it here. If you have problems with Get, do not hesitate to open another issue.

**Closed by jonataslaw** 2020-05-14 14:46 UTC
