### ISSUE TITLE
Get.bottomSheet show/hide keyboard triggers rebuild

### ISSUE THREAD

**Issue by klaszlo8207** [jonataslaw/get#20] opened 2020-03-10 19:27 UTC
I have a **Get.bottomSheet(builder: (_) {**

And some **textfield** in it

When the **keyboard is show/hide on this fields then the widget is rebuild.**.. How can I fix this?
I don't want to rebuild the widget in that case.

Thanks

**Comment by jonataslaw** [comment] 2020-03-11 02:47
> I have a **Get.bottomSheet(builder: (_) {**
> 
> And some **textfield** in it
> 
> When the **keyboard is show/hide on this fields then the widget is rebuild.**.. How can I fix this?
> I don't want to rebuild the widget in that case.
> 
> Thanks

Did you create a separate class for the widget inside your BottomSheet?
BottomSheets are not permanent screens, and you should not treat them as stateful classes, since it is a function. Dart functions have no constructors, and cannot be cached, so any screen refresh will have unexpected effects. This is a matter of good practices that prevent side effects. I

This was a question widely discussed by google engineers about functional programming, you can check it out on issue #19269 from flutter framework.

Also following the Dart documentation, you cannot place Controllers (TextEditController is an example) inside builder methods. The builders methods (build, StreamBuilder, FutureBuilder, BottomSheets, Dialogs) should ONLY receive widgets, for a simple reason: any setState causes a new controller instance to be created, so everything will be deleted, and there will be the mentioned side effect. In addition to causing memory leak. If you open and close the keyboard several times, your app will probably close due to lack of RAM, since you will allocate several controllers in memory that will be lost and can never be closed.

How to solve your problem?

Call your bottomSheet class

```dart
Get.bottomSheet(builder: (_) { return MyBottomSheet();});
```

And create your widget in a Stateful class.

```dart
class MyBottomSheet extends StatefulWidget {
  const MyBottomSheet({Key key}) : super(key: key);

  @override
  _MyBottomSheetState createState() => _MyBottomSheetState();
}

class _MyBottomSheetState extends State<MyBottomSheet> {
  final TextEditingController _editingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Container(
      child: TextField(
        controller: _editingController,
      ),
    );
  }
}
```

Remembering that you would have the same side effect using the bottomSheet of the framework, which incidentally, is untouchable in this package. The dialog has modifications that I found pertinent to improve the performance of the transition, but the BottomSheets of this package just attach the context of Get to the BottomSheet of Flutter.

I hope I have helped you, and that you understood how things work at Dart. Often those who have experience with functional programming get a little confused with this, and the official documentation is still shallow in that sense. I will try to make an addendum there soon.

**Comment by klaszlo8207** [comment] 2020-03-11 05:55
Thanks I will try it!

**Comment by klaszlo8207** [comment] 2020-03-11 07:57
I tried your logic but it is the same as before... Keyboard show/hide triggers rebuild :/

**Comment by jonataslaw** [comment] 2020-03-11 15:56
> I tried your logic but it is the same as before... Keyboard show/hide triggers rebuild :/

Can you provide sample code for me to reproduce?

**Comment by jonataslaw** [comment] 2020-03-17 21:23
Without a clear example, it will not be possible to reproduce this error. Furthermore, the above error does not seem to be related to this library, since in tests, it works exactly as expected. If you encounter an error with this library, do not hesitate to open another issue.
Closing this.

**Closed by jonataslaw** 2020-03-17 21:23 UTC

**Comment by elkhalifte** [comment] 2022-05-14 11:48
thats becz modalsheet uses MediaQuery on build. and keyboard pop up has an effect on this.
