### ISSUE TITLE
Get.arguments  always is null

### ISSUE THREAD

**Issue by Hamidrezana** [jonataslaw/get#164] opened 2020-05-30 04:56 UTC
I am trying to set arguments when trying to navigate. But in second page `Get.arguments` is always null.

```
Get.toNamed(Routes.chats, arguments: 'Hello');
```

and in Chats screen I have `statefulWidget`:
```
class ChatsScreen extends StatefulWidget {
	ChatsScreen() {
    print('args: ${Get.arguments}');
	}
  @override
  _ChatsScreenState createState() => _ChatsScreenState();
}
```  
also in `initState` is `null`:
```
  @override
  void initState() {
    print('args: ${Get.arguments}');
    super.initState();
  }
```

This is my `flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.1 at /home/hamidreza/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/hamidreza/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/hamidreza/Android/Sdk
    • Java binary at: /snap/android-studio/88/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/88/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • C6603 • CB5A1VRUQV • android-arm • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

```

My `get` version is `2.7.1`.

Where is my problem?
Or is it a bug?

**Comment by jonataslaw** [comment] 2020-05-30 05:53
I just created a reproduction example, and it works normally.
Try Flutter clean your project, there is a problem with it, but this is definitely not normal.

**Comment by jonataslaw** [comment] 2020-05-30 05:56
```dart
class First extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Arguments test"),
      ),
      body: RaisedButton(
        onPressed: () {
          Get.toNamed('/second', arguments: 'test');
        },
      ),
    );
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("second ${Get.arguments}"),
      ),
      body: Center(),
    );
  }
}

```

**Comment by Hamidrezana** [comment] 2020-05-30 06:11
I don't know where is the problem. It works in other pages I used but it this page not.
`widget.args` also not work:
```
class ChatsScreen extends StatefulWidget {
  final String args;
  ChatsScreen({this.args});
  @override
  _ChatsScreenState createState() => _ChatsScreenState();
}
```
```
    print('Incoming widget args ${widget.args}');
    print('Incoming Get args ${Get.arguments}');
```

both of them is `null`.

just simple navigating:
```
FlatButton(
  child: Text('go'),
  onPressed: () => Get.toNamed(Routes.chats, arguments: 'hello'),
),
```

**Comment by jonataslaw** [comment] 2020-05-30 06:21
Are you using onGenerateRoute, routes or namedRoutes?

**Comment by Hamidrezana** [comment] 2020-05-30 06:21
I found the problem. My bad.
I didn't define arguments in `onGenerateRoute` for this page.
now `print('Incoming widget args ${widget.args}');` works but `print('Incoming Get args ${Get.arguments}');` is null.

**Comment by jonataslaw** [comment] 2020-05-30 06:25
If you were using namedRoutes there would be no need to pass the arguments to the routes, but with onGenerateRoute this is necessary.
Depending on where you insert Get.arguments, they can be null. I would use it only in the build method, and inside controllers.

**Comment by Hamidrezana** [comment] 2020-05-30 06:26
No, I am using `onGenerateRoute`, So `Get.arguments` only works with `namedRoutes`?

**Comment by jonataslaw** [comment] 2020-05-30 06:49
It works with both, but namedRoutes was created because onGenerateRoutes has some bugs (or it did, I didn't check out the latest stable hotfix). The arguments are taken from the didpush, so technically, if a route has been sent, the arguments will be available even without named routes (with Get.to (Screen ()) you can also send arguments).
For the workflow, this is practically impossible to reproduce, so I suggested the flutter clean, because didPush that records the arguments, there is no way for a route to be pushed, and the arguments are not sent together.
If you had removed a route from the stack, there could be a wrong write, but Get.toNamed is just a didPush, so it must be a problem with hotReload or something.
If you can get a reproduction of this, I’d be happy to review it.

**Comment by Hamidrezana** [comment] 2020-05-30 07:02
I am trying to navigate to chats screen when user open application by notification came from firebase and send data from notification's message.
I already add my codes.
My problem solved by adding arguments in `onGenerateRoute` and get args with `widget.args`.

**Comment by jonataslaw** [comment] 2020-05-30 07:12
Okay, I'm glad you found the solution.
So can I close this issue?

**Comment by Hamidrezana** [comment] 2020-05-30 07:13
tnx for your help.
Yes :)

**Closed** 2020-05-30 07:14 UTC

**Comment by tva77** [comment] 2022-02-09 18:23
@Hamidrezana can you post your final solution, please? Thank you

**Comment by tdsoft** [comment] 2023-08-08 04:52
If someone faces this issue in 2023 when you are using `GetPageRoute` please pass the `RouteSettings settings` parama to the 
 `settings` param in `GetPageRoute`.
Ex:

```
return GetPageRoute<bool?>(
          settings: settings,
          page: () => YourScreen(),
          binding: YourBinding(),
          transition: Transition.downToUp,
        );
```
