### ISSUE TITLE
Duplicate GlobalKey detected in widget tree.

### ISSUE THREAD

**Issue by brianschardt** [jonataslaw/get#116] opened 2020-05-17 17:48 UTC
**Describe the bug**
When navigating through routes I get this error

```Duplicate GlobalKey detected in widget tree.```

**Comment by jonataslaw** [comment] 2020-05-17 19:11
Please make sure you have a GetMaterialApp inside another GetMaterialApp. There can be only one GetMaterialApp in the tree.

**Comment by brianschardt** [comment] 2020-05-18 01:44
Hmm pretty sure I don’t have that

Brian Schardt

**Comment by brianschardt** [comment] 2020-05-18 16:56
This occurs when I route from one screen with a form and the keys are created on the controller to another screen and then back to the screen with the form. The controller is being created again and not disposed of properly hence the duplicate key error. 

Any suggestions?

**Comment by jonataslaw** [comment] 2020-05-18 19:19
> This occurs when I route from one screen with a form and the keys are created on the controller to another screen and then back to the screen with the form. The controller is being created again and not disposed of properly hence the duplicate key error.
> 
> Any suggestions?

The controller is only available when no class uses it anymore, and no class keeps it in memory. Using an init twice could cause this. Are you using GetBuilder or GetX?

If you prefer, I can take a look at these classes by email.

**Comment by INotDisposable** [comment] 2020-05-26 02:43
I get the same issue if I use `Get.lazyPut` to add my controllers to the state manager.  If I register just one instance using `Get.put` then I don't get the error.  It might be important to note that I don't use named routes, I use the code `Get.to(Page());`.  I see in the latest version there is a note about creating a class that extends Bindings to init a controller outside of init.  I don't know how that needs to be set up, but if we can get an example of that it might help too.

Overall, Get is awesome - thank you for this project and the time you put into it!

**Comment by jonataslaw** [comment] 2020-05-26 05:03
> This occurs when I route from one screen with a form and the keys are created on the controller to another screen and then back to the screen with the form. The controller is being created again and not disposed of properly hence the duplicate key error.
> 
> Any suggestions?

It depends a lot on where you are starting the Controllers. Are they inside an init: Controller () method or are you initializing them outside? If you are using outside, it is important to remember that lazyPut is appropriate, and not Get.put, because both in init and outside, the Controller can only be created at the exact moment that a GetBuilder or GetX needs it. The logic of Get's "LazyLoad" is so tight, that the controller is created by Get.find () (there is one internally within each GetBuilder / GetX) and not in Get.lazyPut, which creates only one reference to be used in the future to create an instance that is done the moment someone searches for it.

**Comment by jonataslaw** [comment] 2020-05-26 05:20
> I get the same issue if I use `Get.lazyPut` to add my controllers to the state manager. If I register just one instance using `Get.put` then I don't get the error. It might be important to note that I don't use named routes, I use the code `Get.to(Page());`. I see in the latest version there is a note about creating a class that extends Bindings to init a controller outside of init. I don't know how that needs to be set up, but if we can get an example of that it might help too.
> 
> Overall, Get is awesome - thank you for this project and the time you put into it!

Hi thanks.
You don't need to use named routes to use bindings, the normal route API also accepts it.

Get.to(Second(), binding: SecondBind());

class SecondBind extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<ControllerX>(() => ControllerX());
  }
}

class Second extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('second Route'),
      ),
      body: Center(child: GetX<ControllerX>(
              // init: ControllerX(), you don't need put this
              builder: (_) {
                print("count1 rebuild");
                return Text('${_.count1.value}');
              },
            ),
     )

I'm thinking of creating extensions for vscode/intellij or a CLI to automate this process, and I'm going to treat Get in "layers", where people can just put it in pubspec and use it, or they can split it into Controller/View, or if want to split responsibilities to the extreme, you can split into Controller/View/Bindings/Navigation

As Flutter works with stacks, navigation is an overlapping event, so dialogs, bottomsheets, and snack bars are part of navigation.
That way, Dev will be able to insert the dialog widget into the views folder with its Texts and buttons, he will be able to define his Navigator class in Bindings, and within the navigator class, he will be able to call Get.to/Get.dialog /Get.bottomsheet, with the View folder widget. From the Controller folder, he can call nav.openMainDialog; and open a dialog that is declared in Navigator, but that the UI is in View folder. This will allow the complete separation of View, Business logic, dependency injection and navigation logic, but for the Dev who just wants to program, without worrying about it all, he can create his project normally, and separate the responsibilities according to gain know-how for that.

**Comment by jonataslaw** [comment] 2020-06-01 03:12
I cannot reproduce this in version 2.10.0.
If you face a problem, you can create another issue, or reopen this one.
Closing it.

**Closed by jonataslaw** 2020-06-01 03:12 UTC

**Comment by xEyad** [comment] 2021-01-10 15:34
hello i have this issue too.

basically i have 2 screens each with their own controllers and every one of the controllers contains a `GlobalKey<FormState>` that is used by their respective view (both of them have their own Form widget that uses the controller's key) 
and as described by @brianschardt , this happens when you navigate back and forth from one widget to another

**Comment by alvaroreis** [comment] 2021-04-13 20:08
Estou com o mesmo problema do @xEyad.

**Comment by eduardoflorence** [comment] 2021-04-13 22:06
> Estou com o mesmo problema do @xEyad.

Abra uma nova issue e coloque um código mínimo para que possamos reproduzir o problema e conseguir ajudá-lo.

**Comment by exeptionerror** [comment] 2021-06-28 05:34
All Possible solution added [[Solved] Duplicate GlobalKey detected in widget tree](https://fluttercorner.com/duplicate-globalkey-detected-in-widget-tree/)

**Comment by ardeshir-33033** [comment] 2021-08-10 06:21
> > This occurs when I route from one screen with a form and the keys are created on the controller to another screen and then back to the screen with the form. The controller is being created again and not disposed of properly hence the duplicate key error.
> > Any suggestions?
> 
> It depends a lot on where you are starting the Controllers. Are they inside an init: Controller () method or are you initializing them outside? If you are using outside, it is important to remember that lazyPut is appropriate, and not Get.put, because both in init and outside, the Controller can only be created at the exact moment that a GetBuilder or GetX needs it. The logic of Get's "LazyLoad" is so tight, that the controller is created by Get.find () (there is one internally within each GetBuilder / GetX) and not in Get.lazyPut, which creates only one reference to be used in the future to create an instance that is done the moment someone searches for it.

What if we put our key inside Controller?
I put `  GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>(); ` inside Controllers and use it there.
the problem occurs when  a page pushed for the Second Time Like this 
` Page1 => Page2 => Page3 => Page4 =>Page2` when i move to `Page2` for the Second time I got the Duplicate Error.
any idea how to fix it?

**Comment by sudangrg** [comment] 2021-09-07 04:05
> > > This occurs when I route from one screen with a form and the keys are created on the controller to another screen and then back to the screen with the form. The controller is being created again and not disposed of properly hence the duplicate key error.
> > > Any suggestions?
> > 
> > 
> > It depends a lot on where you are starting the Controllers. Are they inside an init: Controller () method or are you initializing them outside? If you are using outside, it is important to remember that lazyPut is appropriate, and not Get.put, because both in init and outside, the Controller can only be created at the exact moment that a GetBuilder or GetX needs it. The logic of Get's "LazyLoad" is so tight, that the controller is created by Get.find () (there is one internally within each GetBuilder / GetX) and not in Get.lazyPut, which creates only one reference to be used in the future to create an instance that is done the moment someone searches for it.
> 
> What if we put our key inside Controller?
> I put ` GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();` inside Controllers and use it there.
> the problem occurs when a page pushed for the Second Time Like this
> ` Page1 => Page2 => Page3 => Page4 =>Page2` when i move to `Page2` for the Second time I got the Duplicate Error.
> any idea how to fix it?

I am facing the same issue 
did you solved it?

**Comment by RoosterInc** [comment] 2021-09-15 17:25
Come on guys , no fix yet ? .. what do the guys at GetX are doing ?

**Comment by RoosterInc** [comment] 2021-09-18 11:40
I would recommend to stay away from using GetX package , there are so many issues. 
i have encountered yet an other issue. when you use "Border color" property of Get.snakbar() , you will run into 'Null check operator used on null value ' error. if you remove the property, this error magically disappears.

**Comment by oleksii-pimenov** [comment] 2021-09-30 21:30
> > > > This occurs when I route from one screen with a form and the keys are created on the controller to another screen and then back to the screen with the form. The controller is being created again and not disposed of properly hence the duplicate key error.
> > > > Any suggestions?
> > > 
> > > 
> > > It depends a lot on where you are starting the Controllers. Are they inside an init: Controller () method or are you initializing them outside? If you are using outside, it is important to remember that lazyPut is appropriate, and not Get.put, because both in init and outside, the Controller can only be created at the exact moment that a GetBuilder or GetX needs it. The logic of Get's "LazyLoad" is so tight, that the controller is created by Get.find () (there is one internally within each GetBuilder / GetX) and not in Get.lazyPut, which creates only one reference to be used in the future to create an instance that is done the moment someone searches for it.
> > 
> > 
> > What if we put our key inside Controller?
> > I put ` GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();` inside Controllers and use it there.
> > the problem occurs when a page pushed for the Second Time Like this
> > ` Page1 => Page2 => Page3 => Page4 =>Page2` when i move to `Page2` for the Second time I got the Duplicate Error.
> > any idea how to fix it?
> 
> I am facing the same issue did you solved it?

Me to, any workaround with? And why in this case Get.offAll(); is not working?  It should make route stack clean

**Comment by shahidpharm** [comment] 2022-01-21 04:31
Hi,
I was facing the same issue in my project where I used getx. 

My project is responsive UI based. There was no issue with desktop web version, but duplicate GlobalKey error occurs when it comes to tablet/mobile screen size. Because in smaller screen navigation menu bar is converted to a drawer with Hamburger menu icon. When I want to navigate to pages through drawer item it shows duplicate GlobalKey error. It occurs because I used a menuController with scaffoldKey. This scaffoldKey was referenced to every pages under key of scaffold widget.

**To solve this problem I did this in alternate way.**


I have removed scaffoldKey from every pages and menuController.

Instead of that I used appBar under scaffold. Then I added a condition to check whether it is desktop or not. If desktop then it will be replaced with prefrredSize like below.

`return Scaffold (
appBar: (!Responsive.isDesktop(context)) ?   AppBar(title:Text('Home') : 
PreferredSize(
     preferredSize: Size(Get.width, 130),
 
       child: WebMenu()
       ),
     ),
),
drawer: Navigation Drawer(),
body:Container()
);
`
This code added in all pages where required.

Now this is working very nice.

Hope this simple solution will help you.


Thanks
Shahidul

**Comment by DebugTheCode** [comment] 2022-02-22 13:03
**In my case I forgot to register a singleton in my GetIt init function.**

The error occurred when I used BlocProvider with a BlocBuilder. Somewhere in my business logic I was using Connectivity (to check user's internet connection). I forgot to register this: `sl.registerLazySingleton(() => Connectivity());`

**Comment by grobokop** [comment] 2022-05-17 12:31
> > > > > This occurs when I route from one screen with a form and the keys are created on the controller to another screen and then back to the screen with the form. The controller is being created again and not disposed of properly hence the duplicate key error.
> > > > > Any suggestions?
> > > > 
> > > > 
> > > > It depends a lot on where you are starting the Controllers. Are they inside an init: Controller () method or are you initializing them outside? If you are using outside, it is important to remember that lazyPut is appropriate, and not Get.put, because both in init and outside, the Controller can only be created at the exact moment that a GetBuilder or GetX needs it. The logic of Get's "LazyLoad" is so tight, that the controller is created by Get.find () (there is one internally within each GetBuilder / GetX) and not in Get.lazyPut, which creates only one reference to be used in the future to create an instance that is done the moment someone searches for it.
> > > 
> > > 
> > > What if we put our key inside Controller?
> > > I put ` GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();` inside Controllers and use it there.
> > > the problem occurs when a page pushed for the Second Time Like this
> > > ` Page1 => Page2 => Page3 => Page4 =>Page2` when i move to `Page2` for the Second time I got the Duplicate Error.
> > > any idea how to fix it?
> > 
> > 
> > I am facing the same issue did you solved it?
> 
> Me to, any workaround with? And why in this case Get.offAll(); is not working? It should make route stack clean

I was able to resolve that in two ways. Both ways require to re-create controller, so you loose the data in it (which is fine since i also want to remove pages from navigation stack.)
Way 1: inside your view put (Assume i have LoginController) at constructor.
That will ensure you always have a fresh instance of your Controller.
`
var tag = tag = UniqueKey().toString();
Get.put(LoginController(), tag: tag);
`

Way 2 : inside the bindings put `Get.lazyPut(() => LoginController(),fenix: true);//the fenix is important here`
then at route part: `GetPage(name: '/login', page: () {Get.delete<LoginController>(force: true); return const LoginView();}),`  

There are also exists way 3 where you manage your global keys as a map, but i not want to do it since controller recreation is preferred for me.

**Comment by lucasnocete** [comment] 2022-06-01 00:08
I managed to solve it this way, every time I leave the page

Navigator.pushNamedAndRemoveUntil(context, "/route", (r) => false);

**Comment by almogdadjabir** [comment] 2023-01-06 07:53
# @lucasnocete Thanks you bro, you are a lifesaver

**Comment by Sumit258000** [comment] 2023-06-07 11:12
> I managed to solve it this way, every time I leave the page
> 
> Navigator.pushNamedAndRemoveUntil(context, "/route", (r) => false);

But this will remove last route from stack what about if you need to go back to last page? 
Any update on this issue @jonataslaw

**Comment by Sumit258000** [comment] 2023-06-07 11:29
Just a update if I use GetView instead on GetBuilder problem disappears. No idea how but it works.

**Comment by victrome** [comment] 2023-06-13 20:50
I'm having the same issue. Any update?

**Comment by Sumit258000** [comment] 2023-08-04 10:50
@matthewkooshad The only thing you can do is before creating any globalKey in new route delete last route which already defined globalKey. As said above.


> I managed to solve it this way, every time I leave the page
> 
> Navigator.pushNamedAndRemoveUntil(context, "/route", (r) => false);
